Models/Author.cs
namespace Bookish.Models
{
    public class Author
    {
        public int Id { get; set; }
        public string? Name { get; set; }
        public List<Book>? Books { get; set; }
    }
}

Models/Book.cs
namespace Bookish.Models
{
    public class Book
    {
        public int Id { get; set; }
        public string? Title { get; set;}
        public List<Author>? Authors { get; set; }
        public string? CoverImageUrl { get; set; }
        public string? Blurb { get; set; }
        public List<Member>? CheckedOutBy { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace Bookish.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/Member.cs
namespace Bookish.Models
{
    public class Member
    {
        public int Id { get; set; }
        public string? MemberName { get; set; }
        public string? Password { get; set; }
        public List<Book>? CheckedOutBooks { get; set; }
    }
}

Models/Requests/BookRequest.cs
namespace Bookish.Models.Requests
{
    public class BookRequest
    {
        public int Id { get; set; }
        public string? Title { get; set;}
        public List<int>? Authors { get; set; }
        public string? CoverImageUrl { get; set; }
        public string? Blurb { get; set; }
        public List<int>? CheckedOutBy { get; set; }
    }
}

Controllers/BookController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Bookish.Models.Requests;
using Bookish.Models;
using Bookish.Services;

namespace Bookish.Controllers;
[Route("books")]
public class BookController : Controller
{
    private readonly ILogger<BookController> _logger;
    private readonly BookService _bookService;
    private readonly AuthorService _authorService;

    public BookController(ILogger<BookController> logger)
    {
        _logger = logger;
        _bookService = new BookService();
        _authorService = new AuthorService();
    }
    public IActionResult Index()
    {
        List<Book> books = _bookService
            .GetAllBooks()
            .ToList();

        return View(books);
    }

    [HttpPost("")]
    public IActionResult Create([FromForm] BookRequest newBookRequest)
    {
        Book addedBook = _bookService.Create(newBookRequest);

        return RedirectToAction("Index");
    }


    [HttpGet("create")]
    public IActionResult CreateForm()
    {
        List<Author> authors = _authorService
            .GetAllAuthors()
            .ToList();
        List<SelectListItem> selectListAuthors = authors.Select
        (
        a => new SelectListItem { Value = a.Id.ToString(), Text = a.Name }
        )
        .ToList();

        ViewBag.Authors = selectListAuthors;

        return View();
    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bookish.Models;

namespace Bookish.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/MemberController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Bookish.Models;
using Microsoft.EntityFrameworkCore;

namespace Bookish.Controllers;
[Route("members")]
public class MemberController : Controller
{
    private readonly ILogger<MemberController> _logger;

    public MemberController(ILogger<MemberController> logger)
    {
        _logger = logger;
    }
    public IActionResult Index()
    {
        var context = new BookishContext();
        List<Member> members = context.Members
            .Include(b => b.CheckedOutBooks)
            .ToList();

        // return View(books);
        // List<Member>members = new List<Member> 
        // {
        //     new Member 
        //     {
        //         MemberName = "Oli",
        //         CheckedOutBooks = new List<string>{
        //         "Harry Potter 1",
        //         "Harry Potter 2"
        //         }
        //     }

        // };
        return View(members);    
    }

    [HttpPost("")]
    public IActionResult Create([FromForm] Member newMember)
    {
        var context = new BookishContext();
        var addedEntity = context.Members.Add(newMember);

        context.SaveChanges();

        // Member addedBook = addedEntity.Entity;

        return RedirectToAction("Index");
    }


    [HttpGet("create")]
    public IActionResult CreateForm()
    {
        return View();
    }

}

Views/Book/CreateForm.cshtml
@using Bookish.Models.Requests;

@model BookRequest
@{
    ViewData["Title"] = "create";
}

<div class="text-center">
    <h1 class="display-4">Add a book to the library</h1>
    <form asp-controller="Book" asp-action="Create" method="post">
        <label>
            Title
            <input asp-for="Title" type="text">
        </label>
         <label>
            Author
            <select asp-for="Authors" asp-items="@ViewBag.Authors"></select>
        </label>
          <label>
            Blurb
            <input asp-for="Blurb" type="text">
        </label>
          <label>
            Cover Image
            <input asp-for="CoverImageUrl" type="text">
        </label>
        <input type="submit" value= "create">
    </form>
</div>

Views/Book/index.cshtml
@model List<Book>
@{
    ViewData["Title"] = "Book";
}

<div class="text-center">
    <h1 class="display-4">Books</h1>
    <ul style= "list-style-type : none;">
        @foreach (var Book in Model)
        {
            <li>@Book.Title</li>
            <img src="@Book.CoverImageUrl" alt="@Book.Title" width="200px"/>
            <li>By
            @foreach (var author in Book.Authors)
            {
                <li>@author.Name</li>
            }
            </li>
            <li>@Book.Blurb</li>
            <br><br>
            
        }
        
    </ul>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Member/CreateForm.cshtml
@model Member
@{
    ViewData["Title"] = "create";
}

<div class="text-center">
    <h1 class="display-4">Log in</h1>
    <form asp-controller="Member" asp-action="Create" method="post">
        <label>
            Name
            <input asp-for="MemberName" type="text">
        </label>
        <label>
            Password
            <input asp-for="Password" type="password">
        </label>
        <input type="submit" value= "create">
    </form>
</div>

Views/Member/Index.cshtml
@model List<Member>
@{
    ViewData["Title"] = "Member";
}

<div class="text-center">
    <h1 class="display-4">Member</h1>
    <ul style= "list-style-type : none;">
        @foreach (var Member in Model)
        {
            <li>@Member.MemberName</li>
            <li>Books checked out:
                @foreach (var book in Member.CheckedOutBooks)
                {
                    <li>@book.Title</li>
                }
            </li>
            <br><br>  
        }
        
    </ul>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookish</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bookish.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bookish</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Books</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="CreateForm">Add Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Members</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="CreateForm">Register</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Bookish - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>